### ISSUE TITLE
how to produce and consume message at the same file or module （like nats.js）

### ISSUE THREAD

**Issue by samsomlan** [memphisdev/memphis.js#199]
I need to write a server code that consumes messages from clients and produces messages to other clients. how to do that?

**Comment by yanivbh1** [comment]
Hey @samsomlan , 
I suggest to start with our [docs](https://docs.memphis.dev)

**Comment by samsomlan** [comment]
thanks yanivbh1。all the document and example only give the simple example to show how to use producer or consumer independent。 I need to write a server side app， some client app send message to it  ，and it also send some control message to other client base one the message in the queue 。 can you give me a simple example ?

**Comment by yanivbh1** [comment]
Not sure what example do you need, but I am suggesting again to do some reading.
