### ISSUE TITLE
Docs: maxAckDeliveries parameter is documented but no usage examples

### ISSUE THREAD

**Issue by andreieuganox** [memphisdev/memphis.js#201]
**Describe the bug**
maxAckDeliveries parameter is documented here: [Docs](https://docs.memphis.dev/memphis/memphis-broker/concepts/dead-letter).
But there is not a single word on how to specify it.

**Comment by yanivbh1** [comment]
Hey @andreieuganox,
Do you mean this one?
<img width="869" alt="Screenshot 2023-10-13 at 13 36 40" src="https://github.com/memphisdev/memphis.js/assets/70286779/70dccbc1-a7e3-4aca-9b3f-a1484ea19ebf">

From [Memphis JS SDK](https://github.com/memphisdev/memphis.js), but available in any other SDK's README.

**Comment by andreieuganox** [comment]
@yanivbh1 thank you for picking this up. No, referring to another parameter: 

_maxAckDeliveries is the parameter that defines how many times the broker will try to redeliver the same message to the same CG until receiving an "Ack."_ according to docs. And seems default is 10.

**Comment by idanasulinmemphis** [comment]
Fixed on docs, closing this issue.
