### ISSUE TITLE
ajv codes needs to be updated to accept formats in v7

### ISSUE THREAD

**Issue by AhmedWaelElsawy** [memphisdev/memphis.js#245]
**Describe the bug**
can't use {"format":  "date"} in JSON schema because formats in ajv v7 come in separate packages according to this issue
https://github.com/ajv-validator/ajv/issues/1295

**Comment by yanivbh1** [comment]
Hey @AhmedWaelElsawy ,
Thanks for bringing this up. Adding @idanasulinmemphis, @shohamroditimemphis, and @shay23b

**Comment by shohamroditimemphis** [comment]
Hi @AhmedWaelElsawy, I am checking this issue and will update you ASAP. Thanks

**Comment by AhmedWaelElsawy** [comment]
Ok, thanks for the fast response.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shohamroditimemphis** [comment]
Hi, I fixed this issue and this fix will included in the our next release. Thanks for your attention :)
