### ISSUE TITLE
[Feature Request] Close a consumer listener function

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis.js#53]
We need to enable the ability to close a consumer listener in our node.js SDK.
When trying to consume messages by sending a GET request, the listener stays open.

```
const express = require('express');
const memphis = require("memphis-dev");
require('dotenv').config()
var bodyParser = require('body-parser');
var cors = require('cors');
const { default: nodeTest } = require('node:test');
const app = express();
const PORT = 3000;

app.use(cors());

app.use(express.static('public'));
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({
    extended: true
}));

let producer, consumer, myData = [];

(async function () {
    try {
        await memphis.connect({
            host: "broker.sandbox.memphis.dev",
            username: process.env.MEMPHIS_USERNAME,
            connectionToken: process.env.MEMPHIS_CT
        });
        producer = await memphis.producer({
            stationName: "glitch",
            producerName: "myProducer"
        });
        consumer = await memphis.consumer({
            stationName: "glitch",
            consumerName: "myConsumer",
            consumerGroup: ""
        });
        consumer.on("message", message => {
            myData.push(message.getData().toString());
            message.ack();
        });
    } catch (ex) {
        console.log(ex);
        memphis.close();
    }
})();

app.get('/', (req, res) => {
    res.send('Hello World!');
});

app.post('/produce', async function (req, res, next) {
    var msg = req.body.msg;
    await producer.produce({
        message: Buffer.from(msg)
    });
    res.sendStatus(200);
});

app.get('/consume', async function (req, res, next) {
    console.log("CONSUME");

    res.json(myData);
    myData = [];
});

app.listen(PORT, () => console.log(`Server listening on port: ${PORT}`));
```

**Comment by RamGoel** [comment]
Hi @yanivbh1,Can you elaborate a little more on it.

**Comment by yanivbh1** [comment]
Hey @RamGoel ,
@idanasulinmemphis will be able to elaborate more

**Comment by idanasulinmemphis** [comment]
Hi @RamGoel thanks for being interested contributing this feature.

Users making use the Node.js SDK currently lack the ability to close the listener for new incoming messages.
When a user call

`consumer.consume()`

He starts listening for new incoming messages, we want the user will have something like
`consumer.stop()`

Hope it is more clear now, If any questions arise please feel free to ask

**Comment by meyvan** [comment]
I agree with @idanasulinmemphis. The consumer is not closing.

I use Socket-IO to run and authenticate with my clients. Then once the authentication is done, I start Memphis connection and create a consumer as per the authenticated clientID and start sending messages to them.

Once my client says to stop sending messages, I call `memphis.close()` assuming it would stop, but it doesn't

Then when the client asks for me to send message again, I try to create a consumer with sa me clientID, but this time memphis throws an error saying `Error: memphis: Consumer BLAHBLAH at station SAMPLE-STATION : Consumer name has to be unique per station`

The reason it happens because, the `memphis.close()` doesn't actually close the connection and memphis has the same connectionID

**Comment by idanasulinmemphis** [comment]
Hi @meyvan, would you like to fix and contribute?

**Comment by obumnwabude** [comment]
Hi @idanasulinmemphis

> He starts listening for new incoming messages, we want the user will have something like
`consumer.stop()`

With reference to the above, do our other SDKs (maybe in the Go language) support something like that?

If yes, please how do they simply dissociate from listening without destroying the consumer? 

This info might help with implementing the feature here in NodeJS

**Comment by idanasulinmemphis** [comment]
Hi @obumnwabude, in Node.js SDK we are using event emitter to listen for new messages using the consumer.on() function, when calling this function the SDK start to fetch messages every X ms we want this infinite loop to stop
