### ISSUE TITLE
Can we export types?

### ISSUE THREAD

**Issue by obumnwabude** [memphisdev/memphis.js#54]
Currently, only the `MemphisInstance` is exported from _index.ts_

https://github.com/memphisdev/memphis.js/blob/5baba397eeb1dc67c3871c5da883fbb4e60f1a09/src/index.ts#L676

This is good and one can quickly do

```js
const memphis = require('memphis-dev');
```

if they were in NodeJS, OR

```ts
import memphis from 'memphis-dev';
```

if they were in NestJS or any TypeScript build.

However, this deprives the developer of the ability to properly leverage the type system in Nest or TypeScript. We can't import the types of `Consumer` or `Producer` inside our own code. 

Could the source code export types along the `MemphisInstance` ? So maybe `Consumer`, `Producer`, and any other applicable entity,  could be declared as interfaces and the respective implementing classes could be hidden.

**Comment by idanasulinmemphis** [comment]
Thanks for the feedback, we released our Nest support few days ago, and currently the issue described is fixed

**Comment by obumnwabude** [comment]
Thank you for NestJS's support.

I've checked it out and I'm using it. But yet the types are not available. Please check it out

**Comment by yanivbh1** [comment]
@obumnwabude Can you dive into the library? Would be great if you inspect it as well

**Comment by obumnwabude** [comment]
Okay I'll check and revert

**Comment by obumnwabude** [comment]
Thanks @idanasulinmemphis for releasing Nest support. It is a cool avenue to export the types without changing the default only-one-instance export for plain JavaScript. I think exporting the types to NestJS should solve this. I will send a pull request.

**Comment by idanasulinmemphis** [comment]
Types issue has been fixed, thanks @obumnwabude for bringing it into our attention
